# Configuration file for test.py

# Define locations of stellar config files, as well as input and output folders
# Only use '/' as path seperator, even on Windows systems
path_stellar_db: ~/.data/stellar_db/
path_cache: ~/.data/cache/