SIMBAD_fields:
 - ra
 - dec
 - diameter
 - rv_value
 - fe_h
 - rot
 - pmra
 - pmdec
 - plx
 - sp
 - otype
 - flux(U)
 - flux(B)
 - flux(V)
 - flux(G)
 - flux(R)
 - flux(I)
 - flux(J)
 - flux(H)
 - flux(K)

exoplanet_fields:
 - name
 - star_name
 - number_planets
 - star_radius
 - star_t_eff
 - star_log_g
 - star_v_sin_i
 - star_mass
 - metallicity
 - planet_radius
 - planet_mass
 - semi_major_axis
 - inclination
 - eccentricity
 - orbital_period
 - transit_epoch
 - transit_dur